### ISSUE TITLE
Documentations?

### ISSUE THREAD

**Issue by stevefan1999-personal** [luhsra/llfree-rs#1]
I was trying to add this into my own internal kernel project but I was quite confused to begin with this crate. Although it maybe still too early on as I'm still trying to understand the paper

**Comment by wrenger** [comment]
The readme and the paper contain higher-level information about the allocator and its design. 

The source-level documentation can be built with:

```sh
# clone and cd into the repo
cargo doc --open
```

**Comment by wrenger** [comment]
Generally, you maybe want to look at the [Linux integration](https://github.com/luhsra/llfree-linux/tree/master/mm/llfree) as a reference on how LLFree can be added to an OS. There is also a [wrapper](https://github.com/luhsra/llfree-linux/blob/master/mm/llfree/llfree_rs.rs) that exports the interface to the Linux kernel.
